#!/bin/bash
#SBATCH --job-name=ivan_test1.job
#SBATCH -D .
#SBATCH --output=mpi_%j.out
#SBATCH --error=mpi_%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=40
#SBATCH --gres=gpu:1
#SBATCH --time=48:00:00
#Example to send an email for Job notification
#SBATCH --mail-type=all
#SBATCH --mail-user=masmitja@icm.csic.es
module load gcc/8.3.0
module load cuda/10.2
module load cudnn/7.6.4
module load nccl/2.4.8
module load tensorrt/6.0.1
module load openmpi/4.0.1
module load atlas/3.10.3
module load scalapack/2.0.2
module load fftw/3.3.8
module load szip/2.1.1
module load ffmpeg/4.2.1
module load opencv/4.1.1
module load python/3.7.4_ML
python main.py
# This is a first example to run a .py in BSC servers

